version: '3.8'

services:
  neurosync:
    build:
      context: .
      dockerfile: Dockerfile
    image: neurosync:latest
    container_name: neurosync-container
    isolation: hyperv
    # Uncomment the following lines if you need GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      # Optional: Mount a local directory for persistent storage
      - ./data:/app/data
    restart: unless-stopped
    # For interactive mode
    stdin_open: true
    tty: true 